sudo: false
language: python
# command to run tests
install:
  - pip install pipenv --upgrade
  - pipenv run pip install pip==18.0 # fix for pip 18.1 error 
  - pipenv install --dev --skip-lock
cache: pip
jobs:
  include:
    - stage: test
      script:
        - pipenv run py.test --cov-config .coveragerc --verbose --cov-report term --cov-report xml --cov=autoscope tests
      python: '3.6'
    - stage: coverage
      python: 3.6
      script: pipenv run codecov