sudo: false
language: python
# command to run tests
install:
  - pip install pipenv --upgrade
  - pipenv run pip install pip==18.0 # fix for pip 18.1 error 
  - pipenv install --dev --skip-lock
cache: pip
jobs:
  include:
    - stage: test
      script:
        - pipenv run pytest --cov=autoscope tests --cov-report=xml
      python: '3.6'
    - stage: coverage
      python: 3.6
      script: codecov