sudo: false
language: python
# command to run tests
install:
  - pip install pipenv --upgrade
  - pipenv install --dev --skip-lock
cache: pip
jobs:
  include:
    - stage: test
      script:
        - pipenv run pytest --cov=./
      python: '3.6'
    - stage: coverage
      python: 3.6
      script: codecov